// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CoreEventDto {
  final CoreEventKind kind;
  final String? entityId;
  final TransferProgressEventDto? transferProgress;
  final PlatformInt64 occurredAtMs;

  const CoreEventDto({
    required this.kind,
    this.entityId,
    this.transferProgress,
    required this.occurredAtMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      entityId.hashCode ^
      transferProgress.hashCode ^
      occurredAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          entityId == other.entityId &&
          transferProgress == other.transferProgress &&
          occurredAtMs == other.occurredAtMs;
}

enum CoreEventKind {
  coreReady,
  appSnapshotInvalidated,
  peerPresenceChanged,
  conversationChanged,
  messageChanged,
  transferProgress,
  incomingOfferRequiresDecision,
  groupInviteReceived,
  ownDeviceBindingRequested,
  platformRequest,
  notificationRequested,
  coreErrorOccurred,
}

class TransferProgressEventDto {
  final String transferId;
  final String state;
  final BigInt persistedBytes;
  final BigInt totalSize;
  final BigInt bytesPerSecond;
  final BigInt? etaSeconds;
  final String? activeEntryRelativePath;

  const TransferProgressEventDto({
    required this.transferId,
    required this.state,
    required this.persistedBytes,
    required this.totalSize,
    required this.bytesPerSecond,
    this.etaSeconds,
    this.activeEntryRelativePath,
  });

  @override
  int get hashCode =>
      transferId.hashCode ^
      state.hashCode ^
      persistedBytes.hashCode ^
      totalSize.hashCode ^
      bytesPerSecond.hashCode ^
      etaSeconds.hashCode ^
      activeEntryRelativePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgressEventDto &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          state == other.state &&
          persistedBytes == other.persistedBytes &&
          totalSize == other.totalSize &&
          bytesPerSecond == other.bytesPerSecond &&
          etaSeconds == other.etaSeconds &&
          activeEntryRelativePath == other.activeEntryRelativePath;
}
