// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/composer.dart';
import 'api/core.dart';
import 'api/health.dart';

import 'dart:async';
import 'dart:convert';

import 'events.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'platform_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CoreEventDto> dco_decode_StreamSink_core_event_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettingsDto dco_decode_app_settings_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ComposerSourceDto dco_decode_box_autoadd_composer_source_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  StartCoreDto dco_decode_box_autoadd_start_core_dto(dynamic raw);

  @protected
  TransferProgressEventDto dco_decode_box_autoadd_transfer_progress_event_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ClipboardSendDto dco_decode_clipboard_send_dto(dynamic raw);

  @protected
  ComposerSourceDto dco_decode_composer_source_dto(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  CoreErrorDto dco_decode_core_error_dto(dynamic raw);

  @protected
  CoreEventDto dco_decode_core_event_dto(dynamic raw);

  @protected
  CoreEventKind dco_decode_core_event_kind(dynamic raw);

  @protected
  CoreHealthDto dco_decode_core_health_dto(dynamic raw);

  @protected
  CreateGroupDto dco_decode_create_group_dto(dynamic raw);

  @protected
  DeviceIdentityDto dco_decode_device_identity_dto(dynamic raw);

  @protected
  GroupDto dco_decode_group_dto(dynamic raw);

  @protected
  GroupInvitationDto dco_decode_group_invitation_dto(dynamic raw);

  @protected
  GroupMemberDto dco_decode_group_member_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<DeviceIdentityDto> dco_decode_list_device_identity_dto(dynamic raw);

  @protected
  List<GroupInvitationDto> dco_decode_list_group_invitation_dto(dynamic raw);

  @protected
  List<GroupMemberDto> dco_decode_list_group_member_dto(dynamic raw);

  @protected
  List<MessageDeliveryDto> dco_decode_list_message_delivery_dto(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  List<NearbyPeerDto> dco_decode_list_nearby_peer_dto(dynamic raw);

  @protected
  List<OwnDeviceBindingDto> dco_decode_list_own_device_binding_dto(dynamic raw);

  @protected
  List<PeerReceivePolicyDto> dco_decode_list_peer_receive_policy_dto(
    dynamic raw,
  );

  @protected
  List<PlatformRequestDto> dco_decode_list_platform_request_dto(dynamic raw);

  @protected
  List<PreparedReceiveEntryDto> dco_decode_list_prepared_receive_entry_dto(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SourceItemDto> dco_decode_list_source_item_dto(dynamic raw);

  @protected
  List<TransferDto> dco_decode_list_transfer_dto(dynamic raw);

  @protected
  List<TransferEntryDto> dco_decode_list_transfer_entry_dto(dynamic raw);

  @protected
  MessageDeliveryDto dco_decode_message_delivery_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  NearbyPeerDto dco_decode_nearby_peer_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  StartCoreDto? dco_decode_opt_box_autoadd_start_core_dto(dynamic raw);

  @protected
  TransferProgressEventDto?
  dco_decode_opt_box_autoadd_transfer_progress_event_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OwnDeviceBindingDto dco_decode_own_device_binding_dto(dynamic raw);

  @protected
  PeerReceivePolicyDto dco_decode_peer_receive_policy_dto(dynamic raw);

  @protected
  PlatformRequestDto dco_decode_platform_request_dto(dynamic raw);

  @protected
  PreparedReceiveEntryDto dco_decode_prepared_receive_entry_dto(dynamic raw);

  @protected
  SendSourceDto dco_decode_send_source_dto(dynamic raw);

  @protected
  SourceItemDto dco_decode_source_item_dto(dynamic raw);

  @protected
  StartCoreDto dco_decode_start_core_dto(dynamic raw);

  @protected
  TransferDto dco_decode_transfer_dto(dynamic raw);

  @protected
  TransferEntryDto dco_decode_transfer_entry_dto(dynamic raw);

  @protected
  TransferProgressEventDto dco_decode_transfer_progress_event_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateGroupDto dco_decode_update_group_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CoreEventDto> sse_decode_StreamSink_core_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettingsDto sse_decode_app_settings_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ComposerSourceDto sse_decode_box_autoadd_composer_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  StartCoreDto sse_decode_box_autoadd_start_core_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransferProgressEventDto sse_decode_box_autoadd_transfer_progress_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ClipboardSendDto sse_decode_clipboard_send_dto(SseDeserializer deserializer);

  @protected
  ComposerSourceDto sse_decode_composer_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  CoreErrorDto sse_decode_core_error_dto(SseDeserializer deserializer);

  @protected
  CoreEventDto sse_decode_core_event_dto(SseDeserializer deserializer);

  @protected
  CoreEventKind sse_decode_core_event_kind(SseDeserializer deserializer);

  @protected
  CoreHealthDto sse_decode_core_health_dto(SseDeserializer deserializer);

  @protected
  CreateGroupDto sse_decode_create_group_dto(SseDeserializer deserializer);

  @protected
  DeviceIdentityDto sse_decode_device_identity_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupDto sse_decode_group_dto(SseDeserializer deserializer);

  @protected
  GroupInvitationDto sse_decode_group_invitation_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupMemberDto sse_decode_group_member_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceIdentityDto> sse_decode_list_device_identity_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupInvitationDto> sse_decode_list_group_invitation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupMemberDto> sse_decode_list_group_member_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageDeliveryDto> sse_decode_list_message_delivery_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  List<NearbyPeerDto> sse_decode_list_nearby_peer_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<OwnDeviceBindingDto> sse_decode_list_own_device_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerReceivePolicyDto> sse_decode_list_peer_receive_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PlatformRequestDto> sse_decode_list_platform_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PreparedReceiveEntryDto> sse_decode_list_prepared_receive_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SourceItemDto> sse_decode_list_source_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TransferDto> sse_decode_list_transfer_dto(SseDeserializer deserializer);

  @protected
  List<TransferEntryDto> sse_decode_list_transfer_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  MessageDeliveryDto sse_decode_message_delivery_dto(
    SseDeserializer deserializer,
  );

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  NearbyPeerDto sse_decode_nearby_peer_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  StartCoreDto? sse_decode_opt_box_autoadd_start_core_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransferProgressEventDto?
  sse_decode_opt_box_autoadd_transfer_progress_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OwnDeviceBindingDto sse_decode_own_device_binding_dto(
    SseDeserializer deserializer,
  );

  @protected
  PeerReceivePolicyDto sse_decode_peer_receive_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformRequestDto sse_decode_platform_request_dto(
    SseDeserializer deserializer,
  );

  @protected
  PreparedReceiveEntryDto sse_decode_prepared_receive_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  SendSourceDto sse_decode_send_source_dto(SseDeserializer deserializer);

  @protected
  SourceItemDto sse_decode_source_item_dto(SseDeserializer deserializer);

  @protected
  StartCoreDto sse_decode_start_core_dto(SseDeserializer deserializer);

  @protected
  TransferDto sse_decode_transfer_dto(SseDeserializer deserializer);

  @protected
  TransferEntryDto sse_decode_transfer_entry_dto(SseDeserializer deserializer);

  @protected
  TransferProgressEventDto sse_decode_transfer_progress_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateGroupDto sse_decode_update_group_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_core_event_dto_Sse(
    RustStreamSink<CoreEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings_dto(
    AppSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_composer_source_dto(
    ComposerSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_start_core_dto(
    StartCoreDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transfer_progress_event_dto(
    TransferProgressEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_clipboard_send_dto(
    ClipboardSendDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_composer_source_dto(
    ComposerSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_error_dto(CoreErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_core_event_dto(CoreEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_core_event_kind(CoreEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_core_health_dto(CoreHealthDto self, SseSerializer serializer);

  @protected
  void sse_encode_create_group_dto(
    CreateGroupDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_identity_dto(
    DeviceIdentityDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_dto(GroupDto self, SseSerializer serializer);

  @protected
  void sse_encode_group_invitation_dto(
    GroupInvitationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_member_dto(
    GroupMemberDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_identity_dto(
    List<DeviceIdentityDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_invitation_dto(
    List<GroupInvitationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_member_dto(
    List<GroupMemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_delivery_dto(
    List<MessageDeliveryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_nearby_peer_dto(
    List<NearbyPeerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_own_device_binding_dto(
    List<OwnDeviceBindingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_receive_policy_dto(
    List<PeerReceivePolicyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_platform_request_dto(
    List<PlatformRequestDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prepared_receive_entry_dto(
    List<PreparedReceiveEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_item_dto(
    List<SourceItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_dto(
    List<TransferDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transfer_entry_dto(
    List<TransferEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_delivery_dto(
    MessageDeliveryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_nearby_peer_dto(NearbyPeerDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_start_core_dto(
    StartCoreDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transfer_progress_event_dto(
    TransferProgressEventDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_own_device_binding_dto(
    OwnDeviceBindingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_receive_policy_dto(
    PeerReceivePolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_request_dto(
    PlatformRequestDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_prepared_receive_entry_dto(
    PreparedReceiveEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_source_dto(SendSourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_source_item_dto(SourceItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_start_core_dto(StartCoreDto self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_dto(TransferDto self, SseSerializer serializer);

  @protected
  void sse_encode_transfer_entry_dto(
    TransferEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_progress_event_dto(
    TransferProgressEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_group_dto(
    UpdateGroupDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
