// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlatformRequestDto {
  final String requestId;
  final String operation;
  final String uri;
  final String? finalName;

  const PlatformRequestDto({
    required this.requestId,
    required this.operation,
    required this.uri,
    this.finalName,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      operation.hashCode ^
      uri.hashCode ^
      finalName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformRequestDto &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          operation == other.operation &&
          uri == other.uri &&
          finalName == other.finalName;
}
