#include "shell_identity.h"

#include <propkey.h>
#include <propvarutil.h>
#include <shlobj.h>
#include <shobjidl.h>
#include <wrl/client.h>

#include <filesystem>
#include <vector>

namespace {

using Microsoft::WRL::ComPtr;

#ifndef _DEBUG
void RemoveLegacyShortcut(const std::filesystem::path& path) {
  ComPtr<IShellLinkW> link;
  ComPtr<IPersistFile> file;
  ComPtr<IPropertyStore> properties;
  if (FAILED(::CoCreateInstance(CLSID_ShellLink, nullptr, CLSCTX_INPROC_SERVER,
                                IID_PPV_ARGS(&link))) ||
      FAILED(link.As(&file)) || FAILED(file->Load(path.c_str(), STGM_READ)) ||
      FAILED(link.As(&properties))) {
    return;
  }
  PROPVARIANT app_id{};
  const HRESULT read = properties->GetValue(PKEY_AppUserModel_ID, &app_id);
  const bool owned = SUCCEEDED(read) && app_id.vt == VT_LPWSTR &&
      app_id.pwszVal != nullptr && wcscmp(app_id.pwszVal, kAppUserModelId) == 0;
  ::PropVariantClear(&app_id);
  wchar_t target[MAX_PATH]{};
  wchar_t arguments[MAX_PATH]{};
  if (!owned || FAILED(link->GetPath(target, MAX_PATH, nullptr, SLGP_RAWPATH)) ||
      FAILED(link->GetArguments(arguments, MAX_PATH)) || arguments[0] != L'\0' ||
      _wcsicmp(std::filesystem::path(target).filename().c_str(), L"lan_chat.exe") != 0) {
    return;
  }
  file.Reset();
  properties.Reset();
  link.Reset();
  if (::DeleteFileW(path.c_str())) {
    ::SHChangeNotify(SHCNE_DELETE, SHCNF_PATHW, path.c_str(), nullptr);
  }
}
#endif

}  // namespace

HRESULT EnsureShellIdentity(const wchar_t* executable_override, const wchar_t* programs_override) {
  HRESULT result = ::SetCurrentProcessExplicitAppUserModelID(kAppUserModelId);
  if (FAILED(result)) return result;
  std::filesystem::path programs_path;
  if (programs_override != nullptr) {
    programs_path = programs_override;
  } else {
    PWSTR programs = nullptr;
    result = ::SHGetKnownFolderPath(FOLDERID_Programs, KF_FLAG_CREATE, nullptr, &programs);
    if (FAILED(result)) return result;
    programs_path = programs;
    ::CoTaskMemFree(programs);
  }
  const auto shortcut = programs_path / kAppShortcutName;
  std::error_code file_error;
  const bool existed = std::filesystem::exists(shortcut, file_error);
  if (file_error) return HRESULT_FROM_WIN32(static_cast<DWORD>(file_error.value()));
  std::vector<wchar_t> buffer(32768);
  const DWORD length = ::GetModuleFileNameW(nullptr, buffer.data(), static_cast<DWORD>(buffer.size()));
  if (length == 0 || length >= buffer.size()) return E_FAIL;
  const std::filesystem::path executable(executable_override == nullptr ? buffer.data() : executable_override);
  if (!executable.is_absolute() || !std::filesystem::is_regular_file(executable, file_error) ||
      (executable_override != nullptr && _wcsicmp(executable.filename().c_str(), L"lan_chat.exe") != 0)) {
    return E_INVALIDARG;
  }

  ComPtr<IShellLinkW> link;
  ComPtr<IPropertyStore> properties;
  ComPtr<IPersistFile> file;
  result = ::CoCreateInstance(CLSID_ShellLink, nullptr, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&link));
  if (SUCCEEDED(result)) result = link->SetPath(executable.c_str());
  if (SUCCEEDED(result)) result = link->SetWorkingDirectory(executable.parent_path().c_str());
  if (SUCCEEDED(result)) result = link->SetIconLocation(executable.c_str(), 0);
  if (SUCCEEDED(result)) result = link->SetDescription(L"NekoSend");
  if (SUCCEEDED(result)) result = link.As(&properties);
  PROPVARIANT app_id{};
  if (SUCCEEDED(result)) result = ::InitPropVariantFromString(kAppUserModelId, &app_id);
  if (SUCCEEDED(result)) result = properties->SetValue(PKEY_AppUserModel_ID, app_id);
  if (SUCCEEDED(result)) result = properties->Commit();
  ::PropVariantClear(&app_id);
  if (SUCCEEDED(result)) result = link.As(&file);
  if (SUCCEEDED(result)) result = file->Save(shortcut.c_str(), TRUE);
  if (FAILED(result)) return result;
  ::SHChangeNotify(existed ? SHCNE_UPDATEITEM : SHCNE_CREATE, SHCNF_PATHW, shortcut.c_str(), nullptr);
#ifndef _DEBUG
  // Both names were generated by earlier clients with the same shell identity.
  RemoveLegacyShortcut(programs_path / L"LAN Chat.lnk");
  RemoveLegacyShortcut(programs_path / L"\x732B\x732B\x5FEB\x4F20.lnk");
#endif
  return S_OK;
}
