// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<ComposerSourceDto> prepareComposerSource({
  required String path,
  required String kind,
}) => RustLib.instance.api.crateApiComposerPrepareComposerSource(
  path: path,
  kind: kind,
);

Future<SendSourceDto> submitComposerAttachment({
  required String clientOperationId,
  required String conversationId,
  required ComposerSourceDto source,
}) => RustLib.instance.api.crateApiComposerSubmitComposerAttachment(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  source: source,
);

Future<MessageDto> submitComposerText({
  required String clientOperationId,
  required String conversationId,
  required String text,
}) => RustLib.instance.api.crateApiComposerSubmitComposerText(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  text: text,
);

class ComposerSourceDto {
  final String displayName;
  final String kind;
  final BigInt totalSize;
  final List<SourceItemDto> sources;

  const ComposerSourceDto({
    required this.displayName,
    required this.kind,
    required this.totalSize,
    required this.sources,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      kind.hashCode ^
      totalSize.hashCode ^
      sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComposerSourceDto &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          kind == other.kind &&
          totalSize == other.totalSize &&
          sources == other.sources;
}
