// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../events.dart';
import '../frb_generated.dart';
import '../platform_io.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_settings_dto`, `conversation_dto`, `message_delivery_dto`, `message_dto`, `parse_platform`, `parse_source_message_kind`, `platform_name`, `publish_message_result`, `publish_source_result`, `start_network_pair`, `transfer_dto`, `with_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CoreRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Stream<CoreEventDto> subscribeCoreEvents() =>
    RustLib.instance.api.crateApiCoreSubscribeCoreEvents();

List<DeviceIdentityDto> listDeviceIdentities() =>
    RustLib.instance.api.crateApiCoreListDeviceIdentities();

String setDeviceAvatar({
  required String clientOperationId,
  required String avatarId,
}) => RustLib.instance.api.crateApiCoreSetDeviceAvatar(
  clientOperationId: clientOperationId,
  avatarId: avatarId,
);

CoreErrorDto describeCoreError({required String message}) =>
    RustLib.instance.api.crateApiCoreDescribeCoreError(message: message);

String generateClientOperationId() =>
    RustLib.instance.api.crateApiCoreGenerateClientOperationId();

StartCoreDto startCore({
  required String databasePath,
  required String deviceName,
  required String platform,
  required bool enableDiscovery,
}) => RustLib.instance.api.crateApiCoreStartCore(
  databasePath: databasePath,
  deviceName: deviceName,
  platform: platform,
  enableDiscovery: enableDiscovery,
);

ConversationDto openPrivateConversation({
  required String clientOperationId,
  required String peerDeviceId,
}) => RustLib.instance.api.crateApiCoreOpenPrivateConversation(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
);

CreateGroupDto createGroup({
  required String clientOperationId,
  required String name,
  required List<String> memberDeviceIds,
}) => RustLib.instance.api.crateApiCoreCreateGroup(
  clientOperationId: clientOperationId,
  name: name,
  memberDeviceIds: memberDeviceIds,
);

List<GroupInvitationDto> listGroupInvitations() =>
    RustLib.instance.api.crateApiCoreListGroupInvitations();

String? decideGroupInvite({
  required String clientOperationId,
  required String inviteId,
  required bool accept,
}) => RustLib.instance.api.crateApiCoreDecideGroupInvite(
  clientOperationId: clientOperationId,
  inviteId: inviteId,
  accept: accept,
);

GroupDto getGroup({required String groupId}) =>
    RustLib.instance.api.crateApiCoreGetGroup(groupId: groupId);

UpdateGroupDto updateGroup({
  required String clientOperationId,
  required String groupId,
  required BigInt expectedRevision,
  String? name,
  required List<String> addMemberIds,
  required List<String> removeMemberIds,
  String? transferOwnerTo,
  required bool disband,
}) => RustLib.instance.api.crateApiCoreUpdateGroup(
  clientOperationId: clientOperationId,
  groupId: groupId,
  expectedRevision: expectedRevision,
  name: name,
  addMemberIds: addMemberIds,
  removeMemberIds: removeMemberIds,
  transferOwnerTo: transferOwnerTo,
  disband: disband,
);

void leaveGroup({required String clientOperationId, required String groupId}) =>
    RustLib.instance.api.crateApiCoreLeaveGroup(
      clientOperationId: clientOperationId,
      groupId: groupId,
    );

List<OwnDeviceBindingDto> listOwnDeviceBindings({String? state}) =>
    RustLib.instance.api.crateApiCoreListOwnDeviceBindings(state: state);

String requestOwnDeviceBinding({
  required String clientOperationId,
  required String peerDeviceId,
}) => RustLib.instance.api.crateApiCoreRequestOwnDeviceBinding(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
);

String decideOwnDeviceBinding({
  required String clientOperationId,
  required String bindingId,
  required bool accept,
}) => RustLib.instance.api.crateApiCoreDecideOwnDeviceBinding(
  clientOperationId: clientOperationId,
  bindingId: bindingId,
  accept: accept,
);

void removeOwnDeviceBinding({
  required String clientOperationId,
  required String peerDeviceId,
}) => RustLib.instance.api.crateApiCoreRemoveOwnDeviceBinding(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
);

void setClipboardMode({
  required String clientOperationId,
  required String peerDeviceId,
  required String mode,
}) => RustLib.instance.api.crateApiCoreSetClipboardMode(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
  mode: mode,
);

void setDefaultReceiveRef({
  required String clientOperationId,
  String? receiveRef,
}) => RustLib.instance.api.crateApiCoreSetDefaultReceiveRef(
  clientOperationId: clientOperationId,
  receiveRef: receiveRef,
);

AppSettingsDto getAppSettings() =>
    RustLib.instance.api.crateApiCoreGetAppSettings();

AppSettingsDto updateAppSettings({
  required String clientOperationId,
  String? defaultReceivePolicy,
  String? defaultReceiveRef,
  required bool clearDefaultReceiveRef,
  bool? notificationsEnabled,
  bool? closeToTray,
  bool? startOnBoot,
  bool? androidKeepOnline,
  bool? autoOpenReceiveDirectory,
  String? logLevel,
}) => RustLib.instance.api.crateApiCoreUpdateAppSettings(
  clientOperationId: clientOperationId,
  defaultReceivePolicy: defaultReceivePolicy,
  defaultReceiveRef: defaultReceiveRef,
  clearDefaultReceiveRef: clearDefaultReceiveRef,
  notificationsEnabled: notificationsEnabled,
  closeToTray: closeToTray,
  startOnBoot: startOnBoot,
  androidKeepOnline: androidKeepOnline,
  autoOpenReceiveDirectory: autoOpenReceiveDirectory,
  logLevel: logLevel,
);

List<PeerReceivePolicyDto> listPeerReceivePolicies() =>
    RustLib.instance.api.crateApiCoreListPeerReceivePolicies();

void setPeerReceivePolicy({
  required String clientOperationId,
  required String peerDeviceId,
  String? receivePolicyOverride,
}) => RustLib.instance.api.crateApiCoreSetPeerReceivePolicy(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
  receivePolicyOverride: receivePolicyOverride,
);

StartCoreDto updateDeviceName({
  required String clientOperationId,
  required String deviceName,
}) => RustLib.instance.api.crateApiCoreUpdateDeviceName(
  clientOperationId: clientOperationId,
  deviceName: deviceName,
);

ClipboardSendDto submitLocalClipboardText({
  required String clientOperationId,
  required String peerDeviceId,
  required String text,
  required bool automatic,
}) => RustLib.instance.api.crateApiCoreSubmitLocalClipboardText(
  clientOperationId: clientOperationId,
  peerDeviceId: peerDeviceId,
  text: text,
  automatic: automatic,
);

List<ConversationDto> listConversations() =>
    RustLib.instance.api.crateApiCoreListConversations();

void markConversationRead({
  required String clientOperationId,
  required String conversationId,
  required PlatformInt64 throughSortOrder,
}) => RustLib.instance.api.crateApiCoreMarkConversationRead(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  throughSortOrder: throughSortOrder,
);

void deleteConversation({
  required String clientOperationId,
  required String conversationId,
}) => RustLib.instance.api.crateApiCoreDeleteConversation(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
);

List<MessageDto> listMessages({
  required String conversationId,
  required int limit,
}) => RustLib.instance.api.crateApiCoreListMessages(
  conversationId: conversationId,
  limit: limit,
);

List<MessageDeliveryDto> listMessageDeliveries({required String messageId}) =>
    RustLib.instance.api.crateApiCoreListMessageDeliveries(
      messageId: messageId,
    );

MessageDto sendTextMessage({
  required String clientOperationId,
  required String conversationId,
  required String text,
}) => RustLib.instance.api.crateApiCoreSendTextMessage(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  text: text,
);

MessageDto sendClipboardTextMessage({
  required String clientOperationId,
  required String conversationId,
  required String text,
}) => RustLib.instance.api.crateApiCoreSendClipboardTextMessage(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  text: text,
);

SendSourceDto sendSourcePath({
  required String clientOperationId,
  required String conversationId,
  required String sourcePath,
  required String messageKind,
}) => RustLib.instance.api.crateApiCoreSendSourcePath(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  sourcePath: sourcePath,
  messageKind: messageKind,
);

SendSourceDto sendSourceItems({
  required String clientOperationId,
  required String conversationId,
  required String displayName,
  required String messageKind,
  required List<SourceItemDto> sources,
}) => RustLib.instance.api.crateApiCoreSendSourceItems(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  displayName: displayName,
  messageKind: messageKind,
  sources: sources,
);

SendSourceDto sendClipboardImageItems({
  required String clientOperationId,
  required String conversationId,
  required String displayName,
  required List<SourceItemDto> sources,
  required String contentFingerprint,
  required bool automatic,
}) => RustLib.instance.api.crateApiCoreSendClipboardImageItems(
  clientOperationId: clientOperationId,
  conversationId: conversationId,
  displayName: displayName,
  sources: sources,
  contentFingerprint: contentFingerprint,
  automatic: automatic,
);

void replaceTransferSourcePath({
  required String clientOperationId,
  required String transferId,
  required String sourcePath,
}) => RustLib.instance.api.crateApiCoreReplaceTransferSourcePath(
  clientOperationId: clientOperationId,
  transferId: transferId,
  sourcePath: sourcePath,
);

void replaceTransferSourceItems({
  required String clientOperationId,
  required String transferId,
  required List<SourceItemDto> sources,
}) => RustLib.instance.api.crateApiCoreReplaceTransferSourceItems(
  clientOperationId: clientOperationId,
  transferId: transferId,
  sources: sources,
);

void replaceReceiveDestinationPath({
  required String clientOperationId,
  required String transferId,
  required String receiveBaseRef,
}) => RustLib.instance.api.crateApiCoreReplaceReceiveDestinationPath(
  clientOperationId: clientOperationId,
  transferId: transferId,
  receiveBaseRef: receiveBaseRef,
);

void replaceReceiveDestinationPrepared({
  required String clientOperationId,
  required String transferId,
  required String receiveBaseRef,
  required List<PreparedReceiveEntryDto> prepared,
}) => RustLib.instance.api.crateApiCoreReplaceReceiveDestinationPrepared(
  clientOperationId: clientOperationId,
  transferId: transferId,
  receiveBaseRef: receiveBaseRef,
  prepared: prepared,
);

List<TransferDto> listTransfers() =>
    RustLib.instance.api.crateApiCoreListTransfers();

BigInt clearCompletedTransfers({required String clientOperationId}) => RustLib
    .instance
    .api
    .crateApiCoreClearCompletedTransfers(clientOperationId: clientOperationId);

List<TransferEntryDto> listTransferEntries({required String transferId}) =>
    RustLib.instance.api.crateApiCoreListTransferEntries(
      transferId: transferId,
    );

void decideIncomingOffer({
  required String clientOperationId,
  required String transferId,
  required bool accept,
  String? receiveBaseRef,
}) => RustLib.instance.api.crateApiCoreDecideIncomingOffer(
  clientOperationId: clientOperationId,
  transferId: transferId,
  accept: accept,
  receiveBaseRef: receiveBaseRef,
);

void decideIncomingOfferPrepared({
  required String clientOperationId,
  required String transferId,
  required String receiveBaseRef,
  required List<PreparedReceiveEntryDto> prepared,
}) => RustLib.instance.api.crateApiCoreDecideIncomingOfferPrepared(
  clientOperationId: clientOperationId,
  transferId: transferId,
  receiveBaseRef: receiveBaseRef,
  prepared: prepared,
);

void pauseTransfer({
  required String clientOperationId,
  required String transferId,
}) => RustLib.instance.api.crateApiCorePauseTransfer(
  clientOperationId: clientOperationId,
  transferId: transferId,
);

void resumeTransfer({
  required String clientOperationId,
  required String transferId,
}) => RustLib.instance.api.crateApiCoreResumeTransfer(
  clientOperationId: clientOperationId,
  transferId: transferId,
);

void cancelTransfer({
  required String clientOperationId,
  required String transferId,
}) => RustLib.instance.api.crateApiCoreCancelTransfer(
  clientOperationId: clientOperationId,
  transferId: transferId,
);

List<PlatformRequestDto> pollPlatformRequests() =>
    RustLib.instance.api.crateApiCorePollPlatformRequests();

void completePlatformRequest({
  required String requestId,
  int? fd,
  String? value,
  String? error,
}) => RustLib.instance.api.crateApiCoreCompletePlatformRequest(
  requestId: requestId,
  fd: fd,
  value: value,
  error: error,
);

List<NearbyPeerDto> getNearbyPeers() =>
    RustLib.instance.api.crateApiCoreGetNearbyPeers();

StartCoreDto? getLocalProfile() =>
    RustLib.instance.api.crateApiCoreGetLocalProfile();

void shutdownCore() => RustLib.instance.api.crateApiCoreShutdownCore();

class AppSettingsDto {
  final String defaultReceivePolicy;
  final String? defaultReceiveRef;
  final bool notificationsEnabled;
  final bool closeToTray;
  final bool startOnBoot;
  final bool androidKeepOnline;
  final bool autoOpenReceiveDirectory;
  final String logLevel;

  const AppSettingsDto({
    required this.defaultReceivePolicy,
    this.defaultReceiveRef,
    required this.notificationsEnabled,
    required this.closeToTray,
    required this.startOnBoot,
    required this.androidKeepOnline,
    required this.autoOpenReceiveDirectory,
    required this.logLevel,
  });

  @override
  int get hashCode =>
      defaultReceivePolicy.hashCode ^
      defaultReceiveRef.hashCode ^
      notificationsEnabled.hashCode ^
      closeToTray.hashCode ^
      startOnBoot.hashCode ^
      androidKeepOnline.hashCode ^
      autoOpenReceiveDirectory.hashCode ^
      logLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingsDto &&
          runtimeType == other.runtimeType &&
          defaultReceivePolicy == other.defaultReceivePolicy &&
          defaultReceiveRef == other.defaultReceiveRef &&
          notificationsEnabled == other.notificationsEnabled &&
          closeToTray == other.closeToTray &&
          startOnBoot == other.startOnBoot &&
          androidKeepOnline == other.androidKeepOnline &&
          autoOpenReceiveDirectory == other.autoOpenReceiveDirectory &&
          logLevel == other.logLevel;
}

class ClipboardSendDto {
  final String messageId;
  final String eventId;
  final BigInt clipboardSequence;

  const ClipboardSendDto({
    required this.messageId,
    required this.eventId,
    required this.clipboardSequence,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^ eventId.hashCode ^ clipboardSequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipboardSendDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          eventId == other.eventId &&
          clipboardSequence == other.clipboardSequence;
}

class ConversationDto {
  final String conversationId;
  final String title;
  final String? peerDeviceId;
  final String? groupId;
  final bool isGroup;
  final int memberCount;
  final int onlineCount;
  final String? lastMessagePreview;
  final PlatformInt64 lastActivityAtMs;
  final int unreadCount;
  final bool online;

  const ConversationDto({
    required this.conversationId,
    required this.title,
    this.peerDeviceId,
    this.groupId,
    required this.isGroup,
    required this.memberCount,
    required this.onlineCount,
    this.lastMessagePreview,
    required this.lastActivityAtMs,
    required this.unreadCount,
    required this.online,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      title.hashCode ^
      peerDeviceId.hashCode ^
      groupId.hashCode ^
      isGroup.hashCode ^
      memberCount.hashCode ^
      onlineCount.hashCode ^
      lastMessagePreview.hashCode ^
      lastActivityAtMs.hashCode ^
      unreadCount.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          title == other.title &&
          peerDeviceId == other.peerDeviceId &&
          groupId == other.groupId &&
          isGroup == other.isGroup &&
          memberCount == other.memberCount &&
          onlineCount == other.onlineCount &&
          lastMessagePreview == other.lastMessagePreview &&
          lastActivityAtMs == other.lastActivityAtMs &&
          unreadCount == other.unreadCount &&
          online == other.online;
}

class CoreErrorDto {
  final String code;
  final String message;
  final String userMessage;
  final bool recoverable;
  final String? relatedId;

  const CoreErrorDto({
    required this.code,
    required this.message,
    required this.userMessage,
    required this.recoverable,
    this.relatedId,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      message.hashCode ^
      userMessage.hashCode ^
      recoverable.hashCode ^
      relatedId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreErrorDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          userMessage == other.userMessage &&
          recoverable == other.recoverable &&
          relatedId == other.relatedId;
}

class CreateGroupDto {
  final String groupId;
  final String conversationId;
  final List<String> inviteIds;

  const CreateGroupDto({
    required this.groupId,
    required this.conversationId,
    required this.inviteIds,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ conversationId.hashCode ^ inviteIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateGroupDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          conversationId == other.conversationId &&
          inviteIds == other.inviteIds;
}

class DeviceIdentityDto {
  final String deviceId;
  final String deviceName;
  final String avatarId;
  final bool isLocal;

  const DeviceIdentityDto({
    required this.deviceId,
    required this.deviceName,
    required this.avatarId,
    required this.isLocal,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      avatarId.hashCode ^
      isLocal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceIdentityDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          avatarId == other.avatarId &&
          isLocal == other.isLocal;
}

class GroupDto {
  final String groupId;
  final String name;
  final String ownerDeviceId;
  final BigInt revision;
  final String state;
  final String localRole;
  final String localMembership;
  final List<GroupMemberDto> members;

  const GroupDto({
    required this.groupId,
    required this.name,
    required this.ownerDeviceId,
    required this.revision,
    required this.state,
    required this.localRole,
    required this.localMembership,
    required this.members,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      name.hashCode ^
      ownerDeviceId.hashCode ^
      revision.hashCode ^
      state.hashCode ^
      localRole.hashCode ^
      localMembership.hashCode ^
      members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          name == other.name &&
          ownerDeviceId == other.ownerDeviceId &&
          revision == other.revision &&
          state == other.state &&
          localRole == other.localRole &&
          localMembership == other.localMembership &&
          members == other.members;
}

class GroupInvitationDto {
  final String inviteId;
  final String groupId;
  final String groupName;
  final String inviterDeviceId;
  final String inviterName;
  final List<String> memberDeviceIds;
  final PlatformInt64 createdAtMs;

  const GroupInvitationDto({
    required this.inviteId,
    required this.groupId,
    required this.groupName,
    required this.inviterDeviceId,
    required this.inviterName,
    required this.memberDeviceIds,
    required this.createdAtMs,
  });

  @override
  int get hashCode =>
      inviteId.hashCode ^
      groupId.hashCode ^
      groupName.hashCode ^
      inviterDeviceId.hashCode ^
      inviterName.hashCode ^
      memberDeviceIds.hashCode ^
      createdAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupInvitationDto &&
          runtimeType == other.runtimeType &&
          inviteId == other.inviteId &&
          groupId == other.groupId &&
          groupName == other.groupName &&
          inviterDeviceId == other.inviterDeviceId &&
          inviterName == other.inviterName &&
          memberDeviceIds == other.memberDeviceIds &&
          createdAtMs == other.createdAtMs;
}

class GroupMemberDto {
  final String deviceId;
  final String role;
  final String membership;
  final bool online;

  const GroupMemberDto({
    required this.deviceId,
    required this.role,
    required this.membership,
    required this.online,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ role.hashCode ^ membership.hashCode ^ online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          role == other.role &&
          membership == other.membership &&
          online == other.online;
}

class MessageDeliveryDto {
  final String recipientDeviceId;
  final String recipientName;
  final String state;
  final String? failureReason;
  final PlatformInt64 updatedAtMs;
  final bool delivered;

  const MessageDeliveryDto({
    required this.recipientDeviceId,
    required this.recipientName,
    required this.state,
    this.failureReason,
    required this.updatedAtMs,
    required this.delivered,
  });

  @override
  int get hashCode =>
      recipientDeviceId.hashCode ^
      recipientName.hashCode ^
      state.hashCode ^
      failureReason.hashCode ^
      updatedAtMs.hashCode ^
      delivered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDeliveryDto &&
          runtimeType == other.runtimeType &&
          recipientDeviceId == other.recipientDeviceId &&
          recipientName == other.recipientName &&
          state == other.state &&
          failureReason == other.failureReason &&
          updatedAtMs == other.updatedAtMs &&
          delivered == other.delivered;
}

class MessageDto {
  final String messageId;
  final String conversationId;
  final String senderDeviceId;
  final String kind;
  final String state;
  final String text;
  final BigInt? totalSize;
  final int? entryCount;
  final String? transferId;
  final String? transferState;
  final BigInt? persistedBytes;
  final String? localFileRef;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 localSortOrder;
  final int deliveredCount;
  final int deliveryCount;
  final bool outgoing;

  const MessageDto({
    required this.messageId,
    required this.conversationId,
    required this.senderDeviceId,
    required this.kind,
    required this.state,
    required this.text,
    this.totalSize,
    this.entryCount,
    this.transferId,
    this.transferState,
    this.persistedBytes,
    this.localFileRef,
    required this.createdAtMs,
    required this.localSortOrder,
    required this.deliveredCount,
    required this.deliveryCount,
    required this.outgoing,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      conversationId.hashCode ^
      senderDeviceId.hashCode ^
      kind.hashCode ^
      state.hashCode ^
      text.hashCode ^
      totalSize.hashCode ^
      entryCount.hashCode ^
      transferId.hashCode ^
      transferState.hashCode ^
      persistedBytes.hashCode ^
      localFileRef.hashCode ^
      createdAtMs.hashCode ^
      localSortOrder.hashCode ^
      deliveredCount.hashCode ^
      deliveryCount.hashCode ^
      outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          conversationId == other.conversationId &&
          senderDeviceId == other.senderDeviceId &&
          kind == other.kind &&
          state == other.state &&
          text == other.text &&
          totalSize == other.totalSize &&
          entryCount == other.entryCount &&
          transferId == other.transferId &&
          transferState == other.transferState &&
          persistedBytes == other.persistedBytes &&
          localFileRef == other.localFileRef &&
          createdAtMs == other.createdAtMs &&
          localSortOrder == other.localSortOrder &&
          deliveredCount == other.deliveredCount &&
          deliveryCount == other.deliveryCount &&
          outgoing == other.outgoing;
}

class NearbyPeerDto {
  final String deviceId;
  final String deviceName;
  final String platform;
  final String sourceIp;
  final PlatformInt64 lastSeenAtMs;

  const NearbyPeerDto({
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.sourceIp,
    required this.lastSeenAtMs,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      sourceIp.hashCode ^
      lastSeenAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyPeerDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          sourceIp == other.sourceIp &&
          lastSeenAtMs == other.lastSeenAtMs;
}

class OwnDeviceBindingDto {
  final String peerDeviceId;
  final String peerName;
  final String bindingId;
  final String state;
  final String clipboardMode;
  final String requestedByDeviceId;
  final PlatformInt64 createdAtMs;
  final PlatformInt64 updatedAtMs;
  final bool online;

  const OwnDeviceBindingDto({
    required this.peerDeviceId,
    required this.peerName,
    required this.bindingId,
    required this.state,
    required this.clipboardMode,
    required this.requestedByDeviceId,
    required this.createdAtMs,
    required this.updatedAtMs,
    required this.online,
  });

  @override
  int get hashCode =>
      peerDeviceId.hashCode ^
      peerName.hashCode ^
      bindingId.hashCode ^
      state.hashCode ^
      clipboardMode.hashCode ^
      requestedByDeviceId.hashCode ^
      createdAtMs.hashCode ^
      updatedAtMs.hashCode ^
      online.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnDeviceBindingDto &&
          runtimeType == other.runtimeType &&
          peerDeviceId == other.peerDeviceId &&
          peerName == other.peerName &&
          bindingId == other.bindingId &&
          state == other.state &&
          clipboardMode == other.clipboardMode &&
          requestedByDeviceId == other.requestedByDeviceId &&
          createdAtMs == other.createdAtMs &&
          updatedAtMs == other.updatedAtMs &&
          online == other.online;
}

class PeerReceivePolicyDto {
  final String deviceId;
  final String deviceName;
  final String relation;
  final String? receivePolicyOverride;
  final String effectiveReceivePolicy;

  const PeerReceivePolicyDto({
    required this.deviceId,
    required this.deviceName,
    required this.relation,
    this.receivePolicyOverride,
    required this.effectiveReceivePolicy,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      relation.hashCode ^
      receivePolicyOverride.hashCode ^
      effectiveReceivePolicy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerReceivePolicyDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          relation == other.relation &&
          receivePolicyOverride == other.receivePolicyOverride &&
          effectiveReceivePolicy == other.effectiveReceivePolicy;
}

class PreparedReceiveEntryDto {
  final String entryId;
  final String destinationRef;
  final String? partialRef;
  final BigInt persistedOffset;

  const PreparedReceiveEntryDto({
    required this.entryId,
    required this.destinationRef,
    this.partialRef,
    required this.persistedOffset,
  });

  @override
  int get hashCode =>
      entryId.hashCode ^
      destinationRef.hashCode ^
      partialRef.hashCode ^
      persistedOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedReceiveEntryDto &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          destinationRef == other.destinationRef &&
          partialRef == other.partialRef &&
          persistedOffset == other.persistedOffset;
}

class SendSourceDto {
  final String messageId;
  final String transferId;

  const SendSourceDto({required this.messageId, required this.transferId});

  @override
  int get hashCode => messageId.hashCode ^ transferId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendSourceDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          transferId == other.transferId;
}

class SourceItemDto {
  final String entryKind;
  final String? sourceRef;
  final String relativePath;
  final BigInt size;
  final PlatformInt64 modifiedAtMs;

  const SourceItemDto({
    required this.entryKind,
    this.sourceRef,
    required this.relativePath,
    required this.size,
    required this.modifiedAtMs,
  });

  @override
  int get hashCode =>
      entryKind.hashCode ^
      sourceRef.hashCode ^
      relativePath.hashCode ^
      size.hashCode ^
      modifiedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceItemDto &&
          runtimeType == other.runtimeType &&
          entryKind == other.entryKind &&
          sourceRef == other.sourceRef &&
          relativePath == other.relativePath &&
          size == other.size &&
          modifiedAtMs == other.modifiedAtMs;
}

class StartCoreDto {
  final String deviceId;
  final String deviceName;
  final String platform;
  final bool discoveryAvailable;
  final String? discoveryError;

  const StartCoreDto({
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.discoveryAvailable,
    this.discoveryError,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      discoveryAvailable.hashCode ^
      discoveryError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartCoreDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          discoveryAvailable == other.discoveryAvailable &&
          discoveryError == other.discoveryError;
}

class TransferDto {
  final String transferId;
  final String messageId;
  final String conversationId;
  final String peerDeviceId;
  final String direction;
  final String state;
  final String? failureReason;
  final String displayName;
  final BigInt totalSize;
  final int entryCount;
  final BigInt persistedBytes;
  final String? receiveBaseRef;
  final String? localFileRef;
  final bool pausedByUser;

  const TransferDto({
    required this.transferId,
    required this.messageId,
    required this.conversationId,
    required this.peerDeviceId,
    required this.direction,
    required this.state,
    this.failureReason,
    required this.displayName,
    required this.totalSize,
    required this.entryCount,
    required this.persistedBytes,
    this.receiveBaseRef,
    this.localFileRef,
    required this.pausedByUser,
  });

  @override
  int get hashCode =>
      transferId.hashCode ^
      messageId.hashCode ^
      conversationId.hashCode ^
      peerDeviceId.hashCode ^
      direction.hashCode ^
      state.hashCode ^
      failureReason.hashCode ^
      displayName.hashCode ^
      totalSize.hashCode ^
      entryCount.hashCode ^
      persistedBytes.hashCode ^
      receiveBaseRef.hashCode ^
      localFileRef.hashCode ^
      pausedByUser.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferDto &&
          runtimeType == other.runtimeType &&
          transferId == other.transferId &&
          messageId == other.messageId &&
          conversationId == other.conversationId &&
          peerDeviceId == other.peerDeviceId &&
          direction == other.direction &&
          state == other.state &&
          failureReason == other.failureReason &&
          displayName == other.displayName &&
          totalSize == other.totalSize &&
          entryCount == other.entryCount &&
          persistedBytes == other.persistedBytes &&
          receiveBaseRef == other.receiveBaseRef &&
          localFileRef == other.localFileRef &&
          pausedByUser == other.pausedByUser;
}

class TransferEntryDto {
  final String entryId;
  final String entryKind;
  final String relativePath;
  final BigInt size;
  final BigInt persistedOffset;

  const TransferEntryDto({
    required this.entryId,
    required this.entryKind,
    required this.relativePath,
    required this.size,
    required this.persistedOffset,
  });

  @override
  int get hashCode =>
      entryId.hashCode ^
      entryKind.hashCode ^
      relativePath.hashCode ^
      size.hashCode ^
      persistedOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferEntryDto &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          entryKind == other.entryKind &&
          relativePath == other.relativePath &&
          size == other.size &&
          persistedOffset == other.persistedOffset;
}

class UpdateGroupDto {
  final String groupId;
  final BigInt revision;
  final List<String> inviteIds;

  const UpdateGroupDto({
    required this.groupId,
    required this.revision,
    required this.inviteIds,
  });

  @override
  int get hashCode => groupId.hashCode ^ revision.hashCode ^ inviteIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateGroupDto &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          revision == other.revision &&
          inviteIds == other.inviteIds;
}
