// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

CoreHealthDto getCoreHealth() =>
    RustLib.instance.api.crateApiHealthGetCoreHealth();

class CoreHealthDto {
  final String status;
  final String coreVersion;
  final int protocolVersion;

  const CoreHealthDto({
    required this.status,
    required this.coreVersion,
    required this.protocolVersion,
  });

  @override
  int get hashCode =>
      status.hashCode ^ coreVersion.hashCode ^ protocolVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreHealthDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          coreVersion == other.coreVersion &&
          protocolVersion == other.protocolVersion;
}
